BookStore/Models/Author.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks; 


namespace BookStore.Models
{
    public class Author
    {  
        public int Id { get; set; }

        [Required] 
        [StringLength(100, MinimumLength =3)]
        public string Name { get; set; }
    }
}

BookStore/Controllers/AuthorController.cs
using BookStore.Models;
using BookStore.Models.Repo;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Controllers
{
    public class AuthorController : Controller
    {
        private readonly IBooksRepo<Author> _author; 
        public AuthorController(IBooksRepo<Author> author)
        {
            _author = author;   

        }
        // GET: AuthorController
        public ActionResult Index()
        {
            var author =  _author.list(); 
            return View(author);
        }

        // GET: AuthorController/Details/5
        public ActionResult Details(int id)
        {
            var data = _author.Find(id);

            return  View(data);
        }

        // GET: AuthorController/Create
        public ActionResult Create()
        {
            return View();
        }

        //return author model with id for creating 
        public Author getAuthorWithId()
        {
            var author = new Author
            {
                Id = _author.list().Max(f => f.Id) + 1 == null? 1 : _author.list().Max(f => f.Id) + 1,
            };
            //author.Id = _author.list().Max(f => f.Id) + 1;

            return author; 

        }
        // POST: AuthorController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Author author)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _author.Add(author);
                    return RedirectToAction(nameof(Index));
                }
                catch(Exception e)
                {
                    ModelState.AddModelError("", e.Message);
                    return View(author);
                }
            }


            ModelState.AddModelError("", "You should Filled all the required filleds");
            return View("Create", author); 
        }

        // GET: AuthorController/Edit/5
        public ActionResult Edit(int id)
        {
            var author = _author.Find(id);
            return View(author);
        }

        // POST: AuthorController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Author author)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _author.Update(id, author);
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    return View(author);
                }
            }
            ModelState.AddModelError("", "please follow the instruction for all fields ");
            return View(author);
        }

        // GET: AuthorController/Delete/5
        public ActionResult Delete(int id)
        {
            var author = _author.Find(id); 
            return View(author);
        }

        // POST: AuthorController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Author author )
        {
            try
            {

                _author.Delete(id);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(author);
            }
          
        } 

        public ActionResult Search(string value)
        {
            var searched = _author.Search(value);
            return PartialView("_Author", searched);
        }
    }
}

BookStore/Controllers/BookController.cs
using BookStore.Models;
using BookStore.Models.Repo;
using BookStore.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Controllers
{
    public class BookController : Controller
    {
        private readonly IBooksRepo<Book> _book ;
        private  IBooksRepo<Author> _authors;
        private readonly IHostingEnvironment _hosting; 

        public BookController(IBooksRepo<Book> book, IBooksRepo<Author> authors, IHostingEnvironment hosting)
        {
            _book = book;
            _authors = authors;
            _hosting = hosting; 
        }
        // GET: BookController
        public ActionResult  Index()
        {
            var books = _book.list(); 

            return View(books);
        }

        // GET: BookController/Details/5
        public ActionResult Details(int id)
        {
            var book = _book.Find(id); 
            
            return View(book);
        }

        //return model with  id for creating new one 
        public AuthBookViewModel getModelWithId()
        {
            var model = new AuthBookViewModel
            {
               // Id = _book.list().Max(f => f.Id) + 1 == null ? 1 : _book.list().Max(f => f.Id) + 1,
                Authors = FillAuthor(), // get all users to show them in select box 
            };

            return model; 

        }
        // GET: BookController/Create
        public ActionResult Create()
        {
            return View(getModelWithId());
        }

        // POST: BookController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AuthBookViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {   if(model.File == null)
                    {
                        ViewBag.Message = "please Upload Image for the book";
                        return View(getModelWithId());
                    }
                    if (model.AuthorId == -1)
                    {
                        ViewBag.Message = "please Select Author";
                        return View(getModelWithId());
                    }
                    var author = _authors.Find(model.AuthorId);
                    var book = new Book { Id = model.Id, Name = model.Name, PublishDay = model.PublishDay,
                            Author = author, ImageUrl = "/images/" + UploadImage(model) };
                    _book.Add(book);
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    return View(getModelWithId());
                }
            }
            
           
            return View(getModelWithId()); 
        }

        // GET: BookController/Edit/5
        public ActionResult Edit(int id)
        {
            var book = _book.Find(id);
            if (book == null)
                return RedirectToAction(nameof(Index));
            int authorid = book.Author == null ? -1 : book.Author.Id;
            var model = new AuthBookViewModel
            {
                Id = book.Id,
                Name = book.Name,
                PublishDay = book.PublishDay,
                ImageUrl =  book.ImageUrl,
                AuthorId = authorid ,
                Authors = FillAuthor(),
            }; 
            return View(model); 
            
        }

        // POST: BookController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public ActionResult Edit( int id, AuthBookViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                { 
                    if (model.AuthorId == -1)
                    {
                        ViewBag.Message = "Please Select author";
                        return View(getModelWithId());
                    }
                    var author = _authors.Find(model.AuthorId);
                    //if the user didn't edit the image then get the old and add it 
                    string ImageUrl = string.Empty;
                    if (model.File != null)
                    {
                        //delete the old one and upload the new 
                        DeleteImage(model.ImageUrl);
                        ImageUrl = "/images/" + UploadImage(model);
                       
                    }
                    else
                        ImageUrl = model.ImageUrl; 

                    var book = new Book { Id= model.Id, Name = model.Name,
                        PublishDay = model.PublishDay, Author = author,  ImageUrl = ImageUrl };

                    
                    _book.Update(id, book);
                    return RedirectToAction(nameof(Index));
                }
                catch(Exception e)
                {
                    ModelState.AddModelError("", e.Message);
                    return View(getModelWithId());
                }
            }

            ModelState.AddModelError("", "Please Follow Instruction in all fileds");
            return View(getModelWithId()); 
            
        }

        // GET: BookController/Delete/5
        public ActionResult Delete(int id)
        {
            var book = _book.Find(id);
            
            return View(book);
        }

        // POST: BookController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Book model)
        {
            try
            {
                //delete book with its images 
                _book.Delete(id);
                DeleteImage(model.ImageUrl);
                return RedirectToAction(nameof(Index));
            }
            catch(Exception e)
            {
                ViewBag.Message = e.Message;
                return View();
            }
        } 
        public List<Author> FillAuthor()
        {
            var author = _authors.list().ToList();
            author.Insert(0, new Author { Id = -1, Name = " --- Please Choose the Author ---" });

            return author; 
        } 

        public  string UploadImage(AuthBookViewModel model)
        {
            string fileName = string.Empty;
            //chekc if the image uploaded first
            if (model.File != null)
            {
                string uploads = Path.Combine(_hosting.WebRootPath, "images"); //  get the path to put image 
                fileName = model.File.FileName; // get the name of the image 
                string fullpath = Path.Combine(uploads, fileName); // make the full path for the image  
               // get the image from its fill to our project file 
                using(var stream = new FileStream(fullpath, FileMode.Create))
                {
                    model.File.CopyTo(stream);
                }
            }

            return fileName; 
        } 

        //delete an image from the dir 
        public void DeleteImage(string ImageName)
        {
            string path = _hosting.WebRootPath + ImageName;
            if (System.IO.File.Exists(path))
                System.IO.File.Delete(path);
            
        
        } 

        
        //search for books and return it to index page 
        public ActionResult Search(string value)
        {   

            var searched = _book.Search(value);
            return PartialView("_addBook", searched); 
//            return View("Index", searched); 
        }
    }
}

BookStore/Views/Shared/_Author.cshtml
@model IEnumerable<BookStore.Models.Author>


<p>
    <button class="btn btn-primary" onclick="ShowPopUp('@Url.Action("Create", "Author",null, Context.Request.Scheme )' , 'Create New Author')">
        Create New
    </button>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    <button class="btn btn-primary" onclick="ShowPopUp('@Url.Action("Edit", "Author",null, Context.Request.Scheme )' + '/' + @item.Id, 'Edit @item.Name ')">
                        Edit
                    </button>
                    <button class="btn btn-info" onclick="ShowPopUp('@Url.Action("Details", "Author",null, Context.Request.Scheme )' + '/' + @item.Id, 'Details of @item.Name ')">
                        Details
                    </button>
                    <button class="btn btn-danger" onclick="ShowPopUp('@Url.Action("Delete", "Author",null, Context.Request.Scheme )' + '/' + @item.Id, 'Delete @item.Name ')">
                        Delete
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>

BookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Book Store</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />

    </environment>
    
</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Home</a>
                <a asp-area="" asp-controller="Book" asp-action="Index" class="navbar-brand">Books</a>
                <a asp-area="" asp-controller="Author" asp-action="Index" class="navbar-brand">Authors</a>
            </div>
            <div class="navbar-collapse collapse">
            </div>
        </div>
    </nav>

    <div class="modal" tabindex="-1" id="form-modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Modal title</h5>
                </div>
                <div class="modal-body">

                </div>
                <div class="modal-footer">

                </div>
            </div>
        </div>
    </div>


    <div class="container body-content" id="main">
        @*<form class="d-flex" asp-controller="Book" asp-action="Search">
            <button class="btn btn-outline-success" type="submit" style="float:right">Search</button>
            <input  class="form-control me-2" type="search" name="value" placeholder="Search For Book" aria-label="Search" style="float:right">
        </form>*@
        @RenderSection("Search", required:false)
        <div id="render">
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p>&copy; 2022 - Book Store </p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    @*<script src="~/js/site.js" asp-append-version="true"></script>*@
    @RenderSection("Scripts", required: false)
</body>
</html>

BookStore/Views/Shared/_addBook.cshtml
@model IEnumerable<BookStore.Models.Book>

@{ 
   
}
<p>
    <button class="btn btn-primary" onclick="ShowPopUp('@Url.Action("Create", "Book",null, Context.Request.Scheme )', 'New Book')">Create New</button>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PublishDay)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImageUrl)
            </th>
            <th>
                Actions
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Author.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PublishDay)
                </td>
                <td>
                    <img class="img-thumbnail" alt="No Image" style="width:64px; height:44px" src="@Html.DisplayFor(modelItem => item.ImageUrl) " />
                </td>
                <td>
                    <button class="btn btn-primary" onclick="ShowPopUp('@Url.Action("Edit", "Book",null, Context.Request.Scheme )' + '/' + @item.Id, 'Edit @item.Name ')">
                        Edit
                    </button>
                    <button class="btn btn-info" onclick="ShowPopUp('@Url.Action("Details", "Book", null, Context.Request.Scheme)' + '/' + @item.Id, 'Details @item.Name')">
                        Details
                    </button>
                    <button class="btn btn-danger" onclick="ShowPopUp('@Url.Action("Delete", "Book", null, Context.Request.Scheme)' + '/' + @item.Id, 'Delete @item.Name')">
                        Delete
                    </button>

                </td>
            </tr>
        }
    </tbody>
</table>